-- Archivo: INSERTdepartamentos_utf8.sql
-- Asegúrate de abrirlo en UTF-8

SET CLIENT_ENCODING TO 'UTF8';

INSERT INTO c_departamento (id_departamento, d_nombre) VALUES
(1, 'Presidencia municipal'),
(2, 'Síndico'),
(3, 'Regiduría 1'),
(4, 'Regiduría 2'),
(5, 'Regiduría 3'),
(6, 'Regiduría 4'),
(7, 'Regiduría 5'),
(8, 'Regiduría 6'),
(9, 'Regiduría 7'),
(10, 'Regiduría 8'),
(11, 'Regiduría 9'),
(12, 'Regiduría 10'),
(13, 'Regiduría 11'),
(14, 'Regiduría 12'),
(15, 'Secretario particular'),
(16, 'Coordinador de asesores'),
(17, 'Dirección de gobernación'),
(18, 'Secretario técnico'),
(19, 'Dirección general del sistema municipal para el desarrollo integral de la familia'),
(20, 'Titular del órgano interno de control'),
(21, 'Titular de la unidad de substanciación y resolución'),
(22, 'Titular de la unidad de quejas, denuncias e investigación'),
(23, 'Titular de la dirección transparencia y acceso a la información pública'),
(24, 'Dirección general del Instituto Municipal de las Mujeres'),
(25, 'Dirección de planeación'),
(26, 'Comisario de Seguridad Pública'),
(27, 'Dirección de participación ciudadana'),
(28, 'Dirección de comunicación y vinculación'),
(29, 'Secretaría general'),
(30, 'Jefe de departamento de oficialía de partes común'),
(31, 'Jefe de departamento de ediciones y publicaciones'),
(32, 'Cronista del ayuntamiento'),
(33, 'Jefe de departamento de concentración'),
(34, 'Oficial del registro civil'),
(35, 'Tesorería'),
(36, 'Dirección de egresos'),
(37, 'Dirección de ingresos y cobranza'),
(38, 'Dirección de presupuesto y contabilidad'),
(39, 'Dirección de catastro'),
(40, 'Jefe de departamento del ramo 33'),
(41, 'Coordinación de sistemas de información financiera'),
(42, 'Dirección general de ordenamiento territorial y sustentabilidad'),
(43, 'Dirección de desarrollo urbano'),
(44, 'Dirección de infraestructura y obras públicas'),
(45, 'Dirección de ramo 33'),
(46, 'Dirección de medio ambiente y sustentabilidad'),
(47, 'Dirección general de administración y servicios generales'),
(48, 'Dirección de adquisiciones, arrendamientos y servicios'),
(49, 'Dirección de tecnologías de la información'),
(50, 'Dirección de servicios generales y mantenimiento'),
(51, 'Dirección de recursos humanos'),
(52, 'Dirección de patrimonio'),
(53, 'Dirección de almacén general'),
(54, 'Dirección general jurídica y normatividad'),
(55, 'Dirección de lo contencioso'),
(56, 'Dirección de normatividad'),
(57, 'Dirección de lo consultivo y contratos'),
(58, 'Dirección de asuntos laborales'),
(59, 'Dirección general de inclusión social y desarrollo económico'),
(60, 'Jefe de departamento de salud'),
(61, 'Jefe de departamento de educación'),
(62, 'Jefe de departamento de deporte'),
(63, 'Jefe de departamento de cultura'),
(64, 'Jefe de departamento de la juventud'),
(65, 'Jefe de departamento de equidad de género'),
(66, 'Jefe de departamento de diversidad sexual'),
(67, 'Dirección de comercio'),
(68, 'Jefe de departamento de fomento agropecuario, pesca y ganadería'),
(69, 'Jefe de departamento de turismo'),
(70, 'Dirección general de servicios públicos municipales'),
(71, 'Dirección de limpia pública'),
(72, 'Jefe de departamento de alumbrado público'),
(73, 'Jefe de departamento de parques y jardines'),
(74, 'Dirección de protección civil'),
(75, 'Jefe de departamento de panteones públicos'),
(76, 'Jefe de departamento de rastro municipal'),
(77, 'Jefe de departamento de tránsito y vialidad'),
(78, 'Dirección general de agua potable y alcantarillado'),
(79, 'Jefe de departamento técnico de agua potable y alcantarillado'),
(80, 'Jefe de departamento de comercio de agua potable y alcantarillado'),
(81, 'Jefe de departamento administrativo de agua potable y alcantarillado');
